//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VagStatus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Appointment = new HashSet<Appointment>();
            this.CarPart = new HashSet<CarPart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public int ClientId { get; set; }
    
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<CarPart> CarPart { get; set; }
    }
}
