//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VagStatus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPart
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int PartId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Part Part { get; set; }
    }
}
